### ISSUE TITLE
Latest commit did not trigger a container tag+push

### ISSUE THREAD

**Issue by kevcube** [cloudposse/build-harness#364] opened 2023-12-27 22:23 UTC
### Describe the Bug

when I run commands that would use docker containers (i.e. `make pr/readme`) I get this error:

`docker: Error response from daemon: manifest for cloudposse/build-harness:sha-a1e5103 not found: manifest unknown: manifest unknown.`

This sha is the latest commit to main but it appears a build was not triggered.

### Expected Behavior

container tag exists

### Steps to Reproduce

run `make init; make pr/readme` in any terraform module

**Comment by milldr** [comment] 2023-12-27 22:31
Thanks for pointing this out. I've published the latest release so that the current issue should be resolved. We'll look into resolving the cause going forward

@kevcube please let me know if it's working now for you

**Comment by kevcube** [comment] 2023-12-27 22:38
@milldr working now, thanks!

**Closed as completed** 2023-12-27 22:38 UTC
Labels: bug
