### ISSUE TITLE
make 4.4 (oct 31 2022) causes issues with the git submodule resulting in an infinite loop

### ISSUE THREAD

**Issue by nitrocode** [cloudposse/build-harness#333] opened 2022-12-23 20:53 UTC
Found a bug? Maybe our [Slack Community](https://slack.cloudposse.com) can help. 

[![Slack Community](https://slack.cloudposse.com/badge.svg)](https://slack.cloudposse.com)

## Describe the Bug
make 4.4 (oct 31 2022) and 4.4.1 causes issues with the git submodule resulting in an infinite loop

https://ftp.gnu.org/gnu/make/

cc: @Nuru 

## Expected Behavior
It should not be in an infinite loop

## Steps to Reproduce

1. Use the ancient OSX make which is 3.81 version
1. `/usr/bin/make init`
1. Notice that the target exits successfully
1. Use the GNU make by doing `brew install make` to get the latest 4.4 version
1. `/usr/local/bin/make init`
1. Notice the infinite loop

```sh
✗ make SHELL='sh -x' init

+ pwd
+ pwd
+ '[' -d build-harness ']'
+ pwd
+ config --get remote.origin.url
+ sed 's/\.git$//g'
+ sed 's/git@\(.*\):/https:\/\/\1\//g'
+ show -s --format=%aN
+ show -s --format=%aN
+ config --get remote.origin.url
+ sed 's/\.git$//g'
+ sed 's/git@\(.*\):/https:\/\/\1\//g'
+ rev-parse --verify --short HEAD
+ config --get remote.origin.url
+ sed 's/\.git$//g'
+ sed 's/git@\(.*\):/https:\/\/\1\//g'
+ rev-parse --verify --short HEAD
+ rev-parse --verify --short HEAD
+ config --get remote.origin.url
```

## Screenshots
N/A

## Environment (please complete the following information):
- OSX Ventura 13.0
- GNU Make 4.4

## Additional Context
Worked on debugging this with @dudymas on it! Thank you!

Downgrading back to make 4.3 is successful

Commenting out this line prevents the issue

https://github.com/cloudposse/build-harness/blob/72ee8e2eb3525224ab5d6093d4f919d572eef8cd/Makefile#L42

And the `git` module is the specific one that seems to be failing which causes repeating the include.

https://github.com/cloudposse/build-harness/blob/72ee8e2eb3525224ab5d6093d4f919d572eef8cd/modules/git/bootstrap.Makefile#L11-L17

### Option 1: Use OSX make

```shell
/usr/bin/make --version
/usr/bin/make all
```

### Option 2: Brew to pin GNU Make to 4.3

if you do not want to use the older make but also want to pin to 4.3 using homebrew

- [Brew make.rb raw 4.3 formula](https://raw.githubusercontent.com/Homebrew/homebrew-core/9345e061435f18a91437cc5a3db34a90acbb9f1b/Formula/make.rb)
- [Brew make.rb formula](https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/make.rb)

```sh
# uninstall 4.4 make
brew uninstall make
# find your make.rb file
find / -name make.rb
# override the make.rb file with the 4.3 version
wget https://raw.githubusercontent.com/Homebrew/homebrew-core/9345e061435f18a91437cc5a3db34a90acbb9f1b/Formula/make.rb make.rb
# install
brew install make.rb
# finally pin
brew pin make
```

**Comment by nitrocode** [comment] 2023-01-19 22:59
@dudymas this still fails for me

```
$ make --version
make --version
GNU Make 4.4
```

```
rm .build-harness
rm -rf build-harness/
make SHELL='bash -x' BUILD_HARNESS_AUTO_INIT=true all -n
```

Then the infinite loop ensues.

This loops

```
+ pwd
+ uname -s
+ tr '[:upper:]' '[:lower:]'
+ uname -s
+ tr '[:upper:]' '[:lower:]'
+ uname -m
+ sed s/x86_64/amd64/g
+ uname -m
+ sed s/x86_64/amd64/g
+ uname -s
+ tr '[:upper:]' '[:lower:]'
+ uname -m
+ sed s/x86_64/amd64/g
+ uname -s
+ tr '[:upper:]' '[:lower:]'
```

**Comment by nitrocode** [comment] 2023-03-05 22:08
I'm still running into this issue.

My workaround has been to use `/usr/bin/make` which is the old osx version of `make`. However, I keep forgetting to add `/usr/bin` so for now, I will pin back to `4.3` for now until we have a full fix.

**Comment by gurnben** [comment] 2023-12-12 20:06
We also just bumped into this issue upon updating our CI to a newer Jenkins `alpine` agent!

**Comment by Nuru** [comment] 2024-02-02 08:45
Closing this because I cannot reproduce it with Gnu Make 4.4.1. Maybe it got fixed along the way, maybe you had something cached. If this problem recurs, please open a new issue with fresh details.

**Closed as completed by Nuru** 2024-02-02 08:45 UTC
Labels: bug
